apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: webapp
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: nginx
        image: alifaraz7178/nginx:1.0.0
        ports:
        - containerPort: 80
      - name: webapp
        image: alifaraz7178/webapp:1.0.0
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
